---
- name: update authorized_keys
  hosts: "{{ variable_host | defailt('all') }}"
  tasks:
    - name: modify authorized_keys
      become: True
      blockinfile:
        dest: "~{{ ansible_user_id }}/.ssh/authorized_keys"
        owner: "{{ ansible_user_id }}"
        mode: 0600
        create: yes
        backup: yes
        marker: "###{mark} asible maintianed ssh cert###"
        block: |
          #Updated  {{ ansible_date_time.iso8601 }}
          #By       {{ lookup('env', 'USER') }}@{{lookup("pipe","hostname")}}
          cert-authority {{ lookup('file', cafile) }}
